<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Skills;

class SkillsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Array of sample skills
        $skills = [
            'Java',
            'JavaScript',
            'Python',
            'C#',
            'Ruby',
            'PHP',
            'HTML',
            'CSS',
            'React',
            'Angular',
            'Vue.js',
            'SQL',
            'Node.js',
            'C++',
            'Go',
            'Swift',
            'Kotlin',
            'Django',
            'Laravel',
            'Spring',
            'SQL Server',
            'MongoDB',
            'MySQL',
            'PostgreSQL',
            'Git',
            'GitHub',
            'Docker',
            'Kubernetes',
            'Machine Learning',
            'Data Analysis',
            'Artificial Intelligence',
            'Deep Learning',
            'Statistics',
            'Data Visualization',
            'Business Intelligence',
            'Project Management',
            'Agile',
            'Scrum',
            'Team Leadership',
            'Communication',
            'Problem Solving',
            'Time Management',
            'Public Speaking',
            'Negotiation',
            'Critical Thinking',
            'Creative Thinking',
            'Customer Service',
            'Marketing',
            'SEO',
            'Social Media Marketing',
            'Content Writing',
            'Sales',
            'Business Strategy',
            'Research',
            'Teaching',
            'Training',
            'Financial Analysis',
            'Accounting',
            'Auditing',
            'Financial Reporting',
            'Risk Management',
            'Human Resources',
            'Recruitment',
            'Employee Relations',
            'Conflict Resolution',
            'Law',
            'Legal Research',
            'Contract Law',
            'Intellectual Property',
            'Corporate Law',
            'Tax Law',
            'Regulatory Compliance',
            'Cyber Security',
            'Network Security',
            'Cryptography',
            'Cloud Computing',
            'Cloud Architecture',
            'AWS',
            'Azure',
            'Google Cloud',
            'IoT',
            'Embedded Systems',
            'Product Management',
            'UX/UI Design',
            'Web Development',
            'App Development',
            'Game Development',
            'Database Administration',
            'Technical Support',
            'SEO',
            'Graphic Design',
            'Photography',
            'Video Editing',
            'Event Planning',
            'Branding',
            'Public Relations',
            'Advertising',
            'Event Management',
            'Business Development',
            'Supply Chain',
            'Logistics',
            'Operations',
            'Legal Compliance',
            'Manufacturing',
            'Product Design',
            'Industrial Design',
            'Fashion Design',
            'Interior Design',
            'Construction',
            'Engineering',
            'Electrical Engineering',
            'Mechanical Engineering',
            'Chemical Engineering',
            'Civil Engineering',
            'Biomedical Engineering',
            'Architecture',
            'Aerospace Engineering'
        ];

        foreach ($skills as $skill) {
            Skills::create([
                'name' => $skill,
            ]);
        }
    }
}
